# This file gets loaded when an author runs Makefile.PL.
# It is intended to let a new author know which which plugins are required.
# This file was generated by Module::Install::Package.
# See the doc for that module for more information.
require Module::Install
    unless $INC{'Module/Install.pm'};
require Module::Install::AckXXX
    unless $INC{'Module/Install/AckXXX.pm'};
require Module::Install::Base
    unless $INC{'Module/Install/Base.pm'};
require Module::Install::Can
    unless $INC{'Module/Install/Can.pm'};
require Module::Install::Fetch
    unless $INC{'Module/Install/Fetch.pm'};
require Module::Install::Include
    unless $INC{'Module/Install/Include.pm'};
require Module::Install::Makefile
    unless $INC{'Module/Install/Makefile.pm'};
require Module::Install::ManifestSkip
    unless $INC{'Module/Install/ManifestSkip.pm'};
require Module::Install::Metadata
    unless $INC{'Module/Install/Metadata.pm'};
require Module::Install::Package
    unless $INC{'Module/Install/Package.pm'};
require Module::Install::ReadmeFromPod
    unless $INC{'Module/Install/ReadmeFromPod.pm'};
require Module::Install::Stardoc
    unless $INC{'Module/Install/Stardoc.pm'};
require Module::Install::TestML
    unless $INC{'Module/Install/TestML.pm'};
require Module::Install::VersionCheck
    unless $INC{'Module/Install/VersionCheck.pm'};
require Module::Install::Win32
    unless $INC{'Module/Install/Win32.pm'};
require Module::Install::WriteAll
    unless $INC{'Module/Install/WriteAll.pm'};
require Pegex::Base
    unless $INC{'Pegex/Base.pm'};
require Pegex::Grammar
    unless $INC{'Pegex/Grammar.pm'};
require TestML
    unless $INC{'TestML.pm'};
require TestML::Base
    unless $INC{'TestML/Base.pm'};
require TestML::Compiler
    unless $INC{'TestML/Compiler.pm'};
require TestML::Grammar
    unless $INC{'TestML/Grammar.pm'};
require TestML::Library::Debug
    unless $INC{'TestML/Library/Debug.pm'};
require TestML::Library::Standard
    unless $INC{'TestML/Library/Standard.pm'};
require TestML::Runtime
    unless $INC{'TestML/Runtime.pm'};
require TestML::Runtime::TAP
    unless $INC{'TestML/Runtime/TAP.pm'};
1;
